name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      -uses: actions/checkout@v2
      -name: Use node verision 16
      -uses: actions/setup-node@v2
        -with: 
          node-version: '16'
      -run: npm i
      -run: npm run build --prefix client
